config/routes.rb
Rails.application.routes.draw do

  get "/creatures", to: "creatures#index", as: "creatures"
  root "creatures#index"
  get "/creatures/new", to: "creatures#new", as: "new_creature"
  post "creatures", to: "creatures#create"
  get "creatures/:id", to: "creatures#show", as: "creature"
  get "creatures/:id/edit", to: "creatures#edit", as: "edit_creature"
  patch "creatures/:id", to: "creatures#update"
  delete "creatures/:id", to: "creatures#delete", as: "delete_creature"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creature.rb
class Creature < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

  def index
    @creatures = Creature.paginate(:page => params[:page], :per_page => 3)
  end

  def new
    @creature = Creature.new
  end

  def create
    @creature = Creature.new(creature_params)
    if @creature.save
      redirect_to creatures_path
    end
  end

  def show
    @creature = Creature.find(params[:id])
  end

  def edit
    @creature = Creature.find(params[:id])
  end

  def update
    @creature = Creature.find(params[:id])
    if @creature.update(creature_params)
      redirect_to creature_path
    end
  end

  def delete
    @creature = Creature.find(params[:id])
    if @creature.delete
      redirect_to creatures_path
    end
  end

  private
  def creature_params
    params.require(:creature).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/_form.html.erb
<%= form_for @creature do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/creatures/edit.html.erb
<h3>Edit <%= @creature.name %></h3>

<%= render "form" %>

app/views/creatures/index.html.erb
<h1>Creatures</h1>

<div class="row">
  <% @creatures.each do |creature| %>
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title"><%= creature.name %></span>
              <p><%= creature.description.truncate(45) %></p>
            </div>
            <div class="card-action">
              <%= link_to "More about #{creature.name}", creature_path(creature) %>
            </div>
          </div>
        </div>
  <% end %>
</div>
<%= will_paginate @creatures %>

app/views/creatures/new.html.erb
<h3>Create a new Creature</h3>

<%= render "form" %>

app/views/creatures/show.html.erb
<div class="row">
    <div class="col s12 m10 offset-m1">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= @creature.name %></span>
          <p><%= @creature.description %></p>
        </div>
        <div class="card-action">
          <%= link_to "Edit", edit_creature_path %>
          <%= link_to "Delete", delete_creature_path, method: "delete" %>
        </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BogAppTwo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <div class="fixed-action-btn">
        <a class="btn-floating btn-large red">
          <i class="large material-icons">menu</i>
        </a>
        <ul>
          <li><a class="btn-floating green" href="/creatures/new"><i class="material-icons">add</i></a></li>
          <li><a class="btn-floating yellow darken-3" href="/creatures"><i class="material-icons">contacts</i></a></li>
        </ul>
      </div>
      <%= yield %>
    </div>
  </body>
</html>